Add task solution
Elenaz441/NaumenCourse2023 pull request #2
Opened 2023-10-23 10:26 UTC by Elenaz441

2023-10-26 21:58 UTC, vpyzhyanov commented on README.md
> +Сложность O(n) = 3n + mlog(m) + 22m
слишком грубая оценка. Нельзя так это приравнять. За n можно сразу считать количество уникальных слов

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task1/Task1.java
> +        List<User> collAList = collA.stream().toList(); // для быстрого итерирования
это лишнее. Преобразуя в список для "быстрого" итерирования вы уже произвели "медленное" итерирование. А медленное + быстрое явно медленнее, чем просто медленное.

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task1/Task1.java
> +        Set<User> duplicates = new HashSet<>(); // для быстрого добавления
неправильная коллекция

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task1/Task1.java
> +        return duplicates.stream().toList();
потребляете слишком много памяти

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task2/BarmanTask2.java
> +        switch (combo) {
Не понял зачем вам нужно и `Product` и `Combo`. Один из них лишний

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task2/BarmanTask2.java
> +        return result.stream().toList();
лишняя память. В этом случае создавать ещё один список не имеет никакого смысла

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task2/BarmanTask2.java
> +        Map<Long, Combo> ordersHM = new HashMap<>(orders); // hash map для быстрого поиска заказа
Это будет не быстро, т.к. вы кое-что забыли сделать

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task3/WarAndPeace.java
> +        Map<String, Integer> wordsDict = new HashMap<>(); // Удобнее всего здесь использовать для подсчёта слов
это не обоснование. Слово "удобно" - очень абстрактное, а нам нужна конкретика

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task3/WarAndPeace.java
> +        List<Integer> valuesList = new ArrayList<>(); // Понадобится для быстрого итерирования
Зачем?

2023-10-26 21:58 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task3/WarAndPeace.java
> +        printResult(0, 10, valuesList, wordsDict);
Задача решена неправильно. Не найдёт эта функция требуемые слова. Значения wordsDict не уникальны и невозможно однозначно сопоставить частоту использования слова и само слово.

2023-10-28 07:54 UTC, Elenaz441 commented on src/main/java/ru/naumen/collection/task2/BarmanTask2.java
> +        Map<Long, Combo> ordersHM = new HashMap<>(orders); // hash map для быстрого поиска заказа
А почему это будет не быстро? У orders ключи являются типом Long. Или в задании предполагалось, что заказы у нас должны храниться как связка типов <Ticket, Combo>?

2023-11-02 11:21 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task2/BarmanTask2.java
> +        Map<Long, Combo> ordersHM = new HashMap<>(orders); // hash map для быстрого поиска заказа
Похоже я перепутал причину почему это будет не быстро. Имел в виду что нет equals и hashcode, но тут действительно класс Long, у которого они есть.
Тем не менее скорость всё равно крайне низкая, т.к. вы **каждый раз** пробегаетесь по всем `orders` и копируете их в новую коллекцию. Из-за этого увеличивается сложность до O(n) и память до O(n^2)

2023-11-02 11:37 UTC, vpyzhyanov requested changes

2023-11-02 11:37 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task1/Task1.java
> +        return duplicates.stream().toList();
до сих пор актуально. Не надо создавать копию списка, возвращайте сразу `duplicates`, вы же его создавали как раз для этого

2023-11-02 11:37 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task2/BarmanTask2.java
> +        * Сложность функции - O(1) = 1
Это не так

2023-11-02 11:37 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task2/BarmanTask2.java
> +        * Мы находим заказ быстро благодаря использованию hash map (находим за O(1))
Здесь нет никакого `hash map`

2023-11-02 11:37 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task3/WarAndPeace.java
> +        for (int i = 1; i < 11; i++) {
лучше делать более очевидные условия, т.е. `i <= 10`

2023-11-02 11:37 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task3/WarAndPeace.java
> +            for (Map.Entry<String, Integer> entry : wordsDict.entrySet()) {
Зачем вам цикл в цикле? Вы же понимаете, что это уже O(n^2)?

> Queue<Integer> queue, Map<String, Integer> wordsDict

Невозможно однозначно сопоставить эти коллекции. Например слово "это" может использоваться 100 раз в тексте, а слово "другое" - тоже 100 раз.

2023-11-02 11:37 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task3/WarAndPeace.java
> +        Queue<Integer> queueTop = new PriorityQueue<>(Comparator.reverseOrder());
Сортировать только по частоте использования слов - неправильно. Невозможно однозначно определить какому именно слову соответствует это количество

2023-11-02 11:37 UTC, vpyzhyanov commented on src/main/java/ru/naumen/collection/task3/WarAndPeace.java
> +            queueTop.add(entry.getValue());
это не приводит к желаемому результату

2023-11-18 19:32 UTC, closed without merging