Hw4.2 (bot)
Elenaz441/NaumenCourse2023 pull request #4
Opened 2023-11-01 20:51 UTC by Elenaz441

2023-11-09 11:36 UTC, vpyzhyanov requested changes

2023-11-09 11:36 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Bot.java
> +    void startBot();
Зачем этот метод здесь?

2023-11-09 11:36 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Bot.java
> +    Logic logic = new Logic();
Поле в интерфейсе? А вы знаете, что оно **публичное**?

2023-11-12 11:46 UTC, Elenaz441 commented on src/main/java/ru/urfu/Bot.java
> +    void startBot();
Эта функция находится в интерфейсе, так как в классе RunnerBot создаются именно два Бота (тип переменной Bot, а не VkBot или TelegramBot). И у этих переменных вызывается функция startBot. Да, у каждого класса ботов эта функция реализована по-своему. (те скорее это для того, чтобы именно через интерфейс бота запускать бот).

![image](https://github.com/Elenaz441/NaumenCourse2023/assets/102030455/f80f0b84-d68d-4616-8160-607d190394a1)

2023-11-13 19:10 UTC, vpyzhyanov commented on src/main/java/ru/urfu/Bot.java
> +    void startBot();
С таким же успехом можно заменить `Bot` на конкретную реализацию и запускать его по своему.
В данном случае нет необходимости в этом интерфейсе (я имею в виду метод `startBot()`)

2023-11-18 19:33 UTC, closed without merging